In [2]:
import numpy as np

def gauss_pivot(A):
    n = len(A)
    
    for i in range(n):
        pivot = np.argmax(np.abs(A[i:, i])) + i
        A[[i, pivot]] = A[[pivot, i]]
        
        # Eliminação de Gauss
        for j in range(i + 1, n):
            factor = A[j, i] / A[i, i]
            A[j, i:] -= factor * A[i, i:]
            
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (A[i, -1] - np.dot(A[i, i:-1], x[i:])) / A[i, i]
        
    return x


In [3]:
M = np.array([
    [0.0, -3.0, 7.0, 2.0], # 0*x1 - 3*x2 + 7*x3 = 2
    [1.0, 2.0, -1.0, 3.0], # 1*x1 + 2*x2 - 1*x3 = 3
    [5.0, -1.0, 0.0, 2.0]  # 5*x1 - 1*x2 + 0*x3 = 2
])

solucao = gauss_pivot(M.copy())

print("Matriz Aumentada do Sistema:")
print(M)
print("\nSolução (x1, x2, x3):")
print(solucao)


Matriz Aumentada do Sistema:
[[ 0. -3.  7.  2.]
 [ 1.  2. -1.  3.]
 [ 5. -1.  0.  2.]]

Solução (x1, x2, x3):
[0.72580645 1.62903226 0.98387097]
